app/Http/Controllers/clientesController.php
app/Models/Cliente.php
database/migrations/2025_04_10_061315_create_clientes.php
routes/web.php

feat(crudCliente): finalizado Crud cliente

---

resources/views/motoboy/motoboy_edit.blade.php

feito a pagina de edit motoboy

feat(editMotoboy): feito a pagina de edit motoboy

---

app/Http/Controllers/EstadoController.php
app/Models/Estado.php
database/migrations/2025_04_16_113907_create_estados.php
routes/web.php

feito funções crud de estado e rotas

feat(crudEstado): feito funções crud de estado e rotas

---

resources/views/estado/estado_new.blade.php

Feito formulario de cadastro de estado

feat(formEstado): Feito formulario de cadastro de estado

---

resources/views/estado/estado_show.blade.php

feito pagina de listagem de estados

feat(readEstados): feito pagina de listagem de estados

---

resources/views/estado/estado_edit.blade.php

feito página de edit de estado

feat(editEstado): feito página de edit de estado

---

app/Http/Controllers/clientesController.php
app/Models/Cliente.php
app/Models/Telefone.php
resources/views/cliente/cliente_edit.blade.php
resources/views/cliente/cliente_new.blade.php

: feito relação 1:N telefone e cliente e ajustado função de update

feat(telefone)

---

resources/views/auth/login.blade.php
routes/web.php

feito tela de login (apenas a tela)

feat(telaLogin): feito tela de login (apenas a tela)

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/clientesController.php
app/Models/Cliente.php
app/Models/User.php
database/migrations/2025_04_21_165700_add_tipo_to_users_table.php
database/migrations/2025_04_21_174011_alterar_estrutura_clientes.php
resources/views/auth/login.blade.php
resources/views/cliente/cliente_edit.blade.php
routes/web.php

Sprint3 tarefa 10

---

routes/web.php

feat(status): feito rotas de status

feat(status): feito rotas de status

---

app/Models/Status.php
resources/views/status/status_new.blade.php

feat(statusView): feito formulario de cadastro de status

feat(statusView): feito formulario de cadastro de status

---

resources/views/status/status_show.blade.php

feat(statusView): feito pagina de listagem de status

feat(statusView): feito pagina de listagem de status

---

resources/views/status/status_edit.blade.php

feat(statusView): Feito formulario de edição de status

feat(statusView): Feito formulario de edição de status

---

app/Http/Controllers/EntregasController.php
app/Models/Entrega.php
database/migrations/2025_04_24_065033_create_entregas.php
routes/web.php

feat(entregas): feito o crud de entregas

---

app/Models/Entrega.php

feat(entregas): feito relacoes de entregasçõ

---

resources/views/cliente_planoDelivery/cliente_planoDelivery_edit.blade.php

fix(Cliente Plano Delivery): Altera a rota na tela de cliente plano delivery

---

app/Models/Entrega.php
resources/views/entrega/entrega_show.blade.php
routes/web.php

feat(entregas): feito a página de entrega de entregas

feat(entregas): feito a página de entrega de entregas

---

app/Http/Controllers/EntregasController.php
database/migrations/2025_04_24_065033_create_entregas.php
resources/views/entrega/entrega_edit.blade.php
resources/views/entrega/entrega_show.blade.php

feat(entregas): feito pagina de edit de entregas

feat(entregas): feito pagina de edit de entregas

---

database/seeders/DatabaseSeeder.php
database/seeders/TiposUsuarioSeeder.php
routes/web.php

feat(Autenticacao): Adicioan seeder de tipo de usuário, adiciona middleware de autenticação

---

README.md

docs(README): Adiciona documentação dos endpoints de Entrega e Vincular Entrega e Motoboy
